theme: jekyll-theme-cayman


author: "sukritsingh"
description:
  "A searchable D&D 5e creature list."
baseurl: "/bestiary" # the subpath of your site, e.g. /blog/
url: "http://sukritsingh.github.io" # the base hostname & protocol for your site